let defaultData = {
    "zoom": 100,
    "type": "page",
    "index": -1,
    "uuid": -1,
    "playState": false,
    "activeElement": {
        "page": true,
        "title": "预览效果页",
        "endTime": "2019-04-02T05:43:21.148Z",
        "backgroundColor": "#000"
    },
    "page": {
        "page": true,
        "title": "预览效果页",
        "endTime": "2019-04-02T05:43:21.148Z",
        "backgroundColor": "#000"
    },
    "widgets": [{
        "type": "searchComponent",
        "name": "",
        "width": "100%",
        "height": 200,
        "bgColor": "#ffffff",
        "color": "#999999",
        "text": "",
        "belong": "page",
        "animationName": "",
        "placeholder": "搜索商品或店铺",
        "isFixed": false,
        "opacity": 0.8,
        "top": 0,
        "uuid": "0bb201d2b2"
    },{
        "type": "carousel",
        "width": "100%",
        "height": 150,
        "belong": "page",
        "animationName": "",
        "autoplay": 3000,
        "duration": 500,
        "loop": true,
        "textShow": false,
        "show-indicators": true,
        "vertical": false,
        "touchable": false,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/banner1@2x.png",
            "desc": "图文描述",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/banner2@2x.png",
            "desc": "图文描述",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/banner3@2x.png",
            "desc": "图文描述",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 0,
        "uuid": "3cbc08fee1"
    }, {
        "type": "navComponent",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "padding": 10,
        "navType": false,
        "cols": "5",
        "rows": "2",
        "iconShow": true,
        "txtShow": true,
        "loop": false,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/icon_xp.png",
            "desc": "新品上市",
            "width": "88",
            "height": "88",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/icon_yh.png",
            "desc": "特价优惠",
            "width": "88",
            "height": "88",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/icon_pp.png",
            "desc": "品牌街",
            "width": "88",
            "height": "88",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/icon_jf.png",
            "desc": "积分换购",
            "width": "88",
            "height": "88",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/icon_cx.png",
            "desc": "促销活动",
            "width": "88",
            "height": "88",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/icon_rc.png",
            "desc": "日常用品",
            "width": "88",
            "height": "88",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/icon_fs.png",
            "desc": "服饰箱包",
            "width": "88",
            "height": "88",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/icon_jd.png",
            "desc": "品牌家电",
            "width": "88",
            "height": "88",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/icon_jc.png",
            "desc": "家居建材",
            "width": "88",
            "height": "88",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/icon_sx.png",
            "desc": "生鲜水果",
            "width": "88",
            "height": "88",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 0,
        "uuid": "c1bc956bdc"
    }, {
        "type": "noticeBarComponent",
        "width": "100%",
        "height": 200,
        "bgColor": "#ffffff",
        "color": "#000000",
        "text": "苹果将在3月8号上新产品？敬请期待！",
        "belong": "page",
        "animationName": "",
        "mode": "link",
        "left-icon": "volume-o",
        "top": 0,
        "uuid": "a53fc4bfe2"
    }, {
        "type": "blank",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "blankHeight": 10,
        "top": 0,
        "uuid": "0dc9a3748c"
    }, {
        "type": "jigsaw",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "displayType": "2",
        "positionType": "left",
        "ratio": "1:1",
        "scale": 1,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-16.png",
            "desc": "",
            "width": "376",
            "height": "200",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-17.png",
            "desc": "",
            "width": "376",
            "height": "200",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-15.png",
            "desc": "",
            "width": "750",
            "height": "200",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 579,
        "uuid": "60e10a52bg"
    }, {
        "type": "blank",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "blankHeight": 10,
        "top": 0,
        "uuid": "0dc9a3748a"
    }, {
        "type": "carousel",
        "width": "100%",
        "height": 40,
        "belong": "page",
        "animationName": "",
        "autoplay": 3000,
        "duration": 500,
        "loop": true,
        "textShow": false,
        "show-indicators": false,
        "vertical": false,
        "touchable": false,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/top-banner-2.png",
            "desc": "图文描述",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 0,
        "uuid": "e78a01b56a"
    },  {
        "type": "jigsaw",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "displayType": "1",
        "positionType": "left",
        "ratio": "1:1",
        "scale": 1,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/jigsaw-4.jpg",
            "desc": "",
            "width": "320",
            "height": "389",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/jigsaw-5.jpg",
            "desc": "",
            "width": "320",
            "height": "195",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/jigsaw-6.jpg",
            "desc": "",
            "width": "320",
            "height": "195",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 579,
        "uuid": "60e10a52ac"
    }, {
        "type": "navComponent",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "padding": 0,
        "navType": false,
        "cols": "2",
        "rows": "1",
        "iconShow": true,
        "txtShow": false,
        "loop": false,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-1.png",
            "desc": "图标名称",
            "width": "374",
            "height": "380",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-2.png",
            "desc": "图标名称",
            "width": "374",
            "height": "380",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 746,
        "uuid": "0e7939f649"
    }, {
        "type": "navComponent",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "padding": 0,
        "navType": false,
        "cols": "3",
        "rows": "1",
        "iconShow": true,
        "txtShow": false,
        "loop": false,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-3.png",
            "desc": "图标名称",
            "width": "250",
            "height": "230",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-4.png",
            "desc": "图标名称",
            "width": "250",
            "height": "230",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-5.png",
            "desc": "图标名称",
            "width": "250",
            "height": "230",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 728,
        "uuid": "162ff41a6a"
    }, {
        "type": "blank",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "blankHeight": 10,
        "top": 0,
        "uuid": "9ca7537cc0"
    }, {
        "type": "carousel",
        "width": "100%",
        "height": 74,
        "belong": "page",
        "animationName": "",
        "autoplay": 3000,
        "duration": 500,
        "loop": true,
        "textShow": false,
        "show-indicators": false,
        "vertical": false,
        "touchable": false,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/ad@2x.png",
            "desc": "图文描述",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 0,
        "uuid": "0a16fc0eb4"
    }, {
        "type": "blank",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "blankHeight": 10,
        "top": 0,
        "uuid": "9ca7537c09"
    }, {
        "type": "carousel",
        "width": "100%",
        "height": 40,
        "belong": "page",
        "animationName": "",
        "autoplay": 3000,
        "duration": 500,
        "loop": true,
        "textShow": false,
        "show-indicators": false,
        "vertical": false,
        "touchable": false,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/top-banner-1.png",
            "desc": "图文描述",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 1127,
        "uuid": "04ee2ed538"
    }, {
        "type": "jigsaw",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "displayType": "1",
        "positionType": "left",
        "ratio": "1:1",
        "scale": 1,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/jigsaw-1.jpg",
            "desc": "",
            "width": "320",
            "height": "389",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/jigsaw-2.jpg",
            "desc": "",
            "width": "320",
            "height": "195",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/jigsaw-3.jpg",
            "desc": "",
            "width": "320",
            "height": "195",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 930.0000000000001,
        "uuid": "3857711406"
    }, {
        "type": "navComponent",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "padding": 0,
        "navType": false,
        "cols": "2",
        "rows": "1",
        "iconShow": true,
        "txtShow": false,
        "loop": false,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-6.png",
            "desc": "图标名称",
            "width": "375",
            "height": "380",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-7.png",
            "desc": "图标名称",
            "width": "375",
            "height": "380",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 1167,
        "uuid": "86e01cb59f"
    }, {
        "type": "navComponent",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "padding": 0,
        "navType": false,
        "cols": "3",
        "rows": "1",
        "iconShow": true,
        "txtShow": false,
        "loop": false,
        "list": [{
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-8.png",
            "desc": "图标名称",
            "width": "250",
            "height": "230",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-9.png",
            "desc": "图标名称",
            "width": "250",
            "height": "230",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }, {
            "src": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/img-10.png",
            "desc": "图标名称",
            "width": "250",
            "height": "230",
            "link_type": 0, 
            "spu_id": '', 
            "searchList": [], 
            "gc_id_1": 0, 
            "gc_id_2":0,
            "gc_id_3":0,
            "price_between":{"min_price":'', "max_price": ''},
            "goods_label":[],
            "goods_sort":0, 
            "categoryOne": [],
            "categoryTwo": [], 
            "categoryThree": [], 
            "link_url": '', 
            "link_url_type": 1
        }],
        "top": 1267,
        "uuid": "c741b8f0eb"
    }, {
        "type": "blank",
        "width": "100%",
        "height": 200,
        "belong": "page",
        "animationName": "",
        "blankHeight": 20,
        "top": 204,
        "uuid": "dcf0f19762"
    },
    // {
    //     "type": "tabBar",
    //     "name": "",
    //     "width": "100%",
    //     "height": 200,
    //     "belong": "page",
    //     "animationName": "",
    //     "textShow": true,
    //     "iconShow": true,
    //     "active": 0,
    //     "list": [{
    //         "name": "首页",
    //         "icon": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/footer/icon_home.png",
    //         "activedIcon": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/footer/icon_home_select.png",
    //         "link_type": 0, 
    //         "spu_id": '', 
    //         "searchList": [], 
    //         "gc_id_1": 0, 
    //         "gc_id_2":0,
    //         "gc_id_3":0,
    //         "price_between":{"min_price":'', "max_price": ''},
    //         "goods_label":[],
    //         "goods_sort":0, 
    //         "categoryOne": [],
    //         "categoryTwo": [], 
    //         "categoryThree": [], 
    //         "link_url": '', 
    //         "link_url_type": 1
    //     }, {
    //         "name": "分类",
    //         "icon": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/footer/icon_fenlei.png",
    //         "activedIcon": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/footer/icon_fenlei_select.png",
    //         "link_type": 0, 
    //         "spu_id": '', 
    //         "searchList": [], 
    //         "gc_id_1": 0, 
    //         "gc_id_2":0,
    //         "gc_id_3":0,
    //         "price_between":{"min_price":'', "max_price": ''},
    //         "goods_label":[],
    //         "goods_sort":0, 
    //         "categoryOne": [],
    //         "categoryTwo": [], 
    //         "categoryThree": [], 
    //         "link_url": '', 
    //         "link_url_type": 1
    //     }, {
    //         "name": "发现",
    //         "icon": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/footer/icon_find.png",
    //         "activedIcon": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/footer/icon_find_select.png",
    //         "link_type": 0, 
    //         "spu_id": '', 
    //         "searchList": [], 
    //         "gc_id_1": 0, 
    //         "gc_id_2":0,
    //         "gc_id_3":0,
    //         "price_between":{"min_price":'', "max_price": ''},
    //         "goods_label":[],
    //         "goods_sort":0, 
    //         "categoryOne": [],
    //         "categoryTwo": [], 
    //         "categoryThree": [], 
    //         "link_url": '', 
    //         "link_url_type": 1
    //     }, {
    //         "name": "购物车",
    //         "icon": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/footer/icon_car.png",
    //         "activedIcon": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/footer/icon_car_select.png",
    //         "link_type": 0, 
    //         "spu_id": '', 
    //         "searchList": [], 
    //         "gc_id_1": 0, 
    //         "gc_id_2":0,
    //         "gc_id_3":0,
    //         "price_between":{"min_price":'', "max_price": ''},
    //         "goods_label":[],
    //         "goods_sort":0, 
    //         "categoryOne": [],
    //         "categoryTwo": [], 
    //         "categoryThree": [], 
    //         "link_url": '', 
    //         "link_url_type": 1
    //     }, {
    //         "name": "我的",
    //         "icon": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/footer/icon_own.png",
    //         "activedIcon": "https://wsyjtest-1257062727.cos.ap-chengdu.myqcloud.com/front_static/footer/icon_own_select.png",
    //         "link_type": 0, 
    //         "spu_id": '', 
    //         "searchList": [], 
    //         "gc_id_1": 0, 
    //         "gc_id_2":0,
    //         "gc_id_3":0,
    //         "price_between":{"min_price":'', "max_price": ''},
    //         "goods_label":[],
    //         "goods_sort":0, 
    //         "categoryOne": [],
    //         "categoryTwo": [], 
    //         "categoryThree": [], 
    //         "link_url": '', 
    //         "link_url_type": 1
    //     }],
    //     "top": 154,
    //     "uuid": "9d265868ee"
    // }
    ],
    "top": 0
}


export { defaultData }